"type: snippet":
- any:
  - changed-files:
    - any-glob-to-any-file: src/main/kotlin/codecollection/snippets/**

"type: algorithm":
- any:
  - changed-files:
    - any-glob-to-any-file: src/main/kotlin/codecollection/algorithms/**

"type: kotlinfeature":
- any:
  - changed-files:
    - any-glob-to-any-file: src/main/kotlin/codecollection/kotlinfeatures/**

"type: ci/cd":
- any: 
  - changed-files:
    - any-glob-to-any-file: 
      - gradle/**
      - build.gradle*
      - settings.gradle*
      - gradle.properties
